ALTER TABLE song_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE creator_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE partial_level_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE level_list_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE level_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE profile_meta ADD COLUMN absent BOOL NOT NULL DEFAULT FALSE;